site_url: https://stijnbiemans.netlify.app
display_url: https://stijnbiemans.netlify.app

search: true

backend:
  name: git-gateway
  repo: iroQuai/stijnbiemans.nl
  branch: 'main'

locale: 'nl'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/images
public_folder: /images

collections:
  - name: 'post'
    label: 'berichten'
    label_singular: 'bericht'
    folder: 'content/post'
    preview_path: "post/{{year}}{{month}}{{day}}-{{slug}}"
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum van publicatie", name: "date", widget: "datetime"}
      - { label: "Draft", name: "draft", widget: "boolean", default: true }   
      - label: 'categories'
        name: 'categories'
        widget: "list"
        allow_add: true
        add_to_top: true
        collapsed: true
        field: {label: categories, name: categories, widget: string}   
      - {label: "Inhoud", name: "body", widget: "markdown"}
      - label: 'tags'
        name: 'tags'
        widget: "list"
        allow_add: true
        add_to_top: true
        collapsed: true
        required: false
        field: {label: tags, name: tags, widget: string}
      - {label: "Featured Image", name: "image", widget: "image"}



  - name: 'page'
    label: 'paginas'
    label_singular: 'pagina'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'omschrijving', name: 'description', widget: 'string', required: false}
      - { label: "Draft", name: "draft", widget: "boolean", default: true }   
      - { label: 'inhoud', name: 'body', widget: 'markdown' }
      - label: "Featured Image"
        name: "featured image"
        widget: "image"
        choose_url: true
        default: "/images/page/{{slug}}_featured.jpg"
        required: false
        media_library:
          config:
            multiple: true

  - name: categories
    label: categories
    label_singular: 'categorie'
    folder: content/categories
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        hint: "om een of andere reden moet je bij aanmaken de slug gebruiken in dit veld. Daarna kan je het aanpassen naar iedere gewenste titel"
      - label: slug
        name: slug
        widget: string
        hint: "de categorie zoals die ook in de posts beschreven wordt"
      - label: omschrijving
        name: description
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        choose_url: false
        default: "featured.jpg"
        media_library:
          config:
            multiple: false