site_url: https://stijnbiemans.netlify.app
display_url: https://stijnbiemans.netlify.app

search: true

backend:
  name: git-gateway
  repo: iroQuai/stijnbiemans.nl
  branch: 'main'


slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/images
public_folder: /images

collections:
  - name: 'post'
    label: 'berichten'
    folder: 'content/post'
    # preview_path: "post/{{year}}{{month}}{{day}}-{{slug}}"
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'Titel', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'select', options: ["blog", "media"] }
      - { label: 'Publish Date', name: 'datum', widget: 'datetime' }
      - { label: 'Description', name: 'omschrijving', widget: 'string' }
      - { label: 'Body', name: 'inhoud', widget: 'markdown' }
      - label: "Featured Image"
        name: "featured image"
        widget: "image"
        choose_url: true
        default: "/images/post/{{slug}}_featured.jpg"
        media_library:
          config:
            multiple: true

  - name: 'page'
    label: 'Paginas'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'titel', widget: 'string' }
      - { label: 'Description', name: 'omschrijving', widget: 'string' }
      - { label: 'Body', name: 'inhoud', widget: 'markdown' }
      - label: "Featured Image"
        name: "featured image"
        widget: "image"
        choose_url: true
        default: "/images/page/{{slug}}_featured.jpg"
        media_library:
          config:
            multiple: true

  - name: categories
    label: categories
    label_singular: 'categorie'
    folder: content/categories
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    fields:
      - label: Title
        name: title
        widget: string
      - label: slug
        name: slug
        widget: string
      - label: description
        name: omschrijving
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        choose_url: false
        default: "featured.jpg"
        media_library:
          config:
            multiple: false